import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/global/Navbar';
import ReactQueryProvider from '@/context/ReactQueryProvider';
import AuthProvider from '@/context/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className={`${inter.className} h-screen`}>
        <AuthProvider>
          <ReactQueryProvider>
            <header className='sticky top-0 z-40 bg-base-100/20 backdrop-blur-sm px-5'>
              <Navbar />
            </header>
            <main className='flex flex-col items-center justify-between lg:max-w-screen-xl lg:mx-auto h-[calc(100vh-4rem)]'>
              {children}
            </main>
            <div id='portal'></div>
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
