import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/global/Navbar';
import ReactQueryProvider from '@/context/ReactQueryProvider';
import AuthProvider from '@/context/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className={inter.className}>
        <AuthProvider>
          <ReactQueryProvider>
            <header className='top-0 bg-white border-b z-[999]'>
              <Navbar />
            </header>
            <main className='flex min-h-screen flex-col items-center justify-between p-24'>
              {children}
            </main>
            <div id='portal'></div>
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
